
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 25.4.0 - arm64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/FindWrapAtomic.cmake:36 (check_cxx_source_compiles)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:145 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/Qt6Config.cmake:196 (find_package)"
      - "CMakeLists.txt:8 (find_package)"
    checks:
      - "Performing Test HAVE_STDATOMIC"
    directories:
      source: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-k6LxVV"
      binary: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-k6LxVV"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/include"
      CMAKE_MODULE_PATH: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/platforms;/Users/stahlber/Projects/emsdk/upstream/emscripten/cmake/Modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_STDATOMIC"
      cached: true
      stdout: |
        Change Dir: '/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-k6LxVV'
        
        Run Build Command(s): /opt/homebrew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_bb87c/fast
        /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_bb87c.dir/build.make CMakeFiles/cmTC_bb87c.dir/build
        Building CXX object CMakeFiles/cmTC_bb87c.dir/src.cxx.o
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -DHAVE_STDATOMIC  -std=gnu++17 -MD -MT CMakeFiles/cmTC_bb87c.dir/src.cxx.o -MF CMakeFiles/cmTC_bb87c.dir/src.cxx.o.d -o CMakeFiles/cmTC_bb87c.dir/src.cxx.o -c /Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-k6LxVV/src.cxx
        Linking CXX executable cmTC_bb87c.js
        /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bb87c.dir/link.txt --verbose=1
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -L/usr/local/include  @CMakeFiles/cmTC_bb87c.dir/objects1.rsp -o cmTC_bb87c.js
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/FindWrapRt.cmake:23 (check_cxx_source_compiles)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:145 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/Qt6Config.cmake:196 (find_package)"
      - "CMakeLists.txt:8 (find_package)"
    checks:
      - "Performing Test HAVE_GETTIME"
    directories:
      source: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-ZhDgO4"
      binary: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-ZhDgO4"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/include"
      CMAKE_MODULE_PATH: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/platforms;/Users/stahlber/Projects/emsdk/upstream/emscripten/cmake/Modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_GETTIME"
      cached: true
      stdout: |
        Change Dir: '/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-ZhDgO4'
        
        Run Build Command(s): /opt/homebrew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_514ca/fast
        /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_514ca.dir/build.make CMakeFiles/cmTC_514ca.dir/build
        Building CXX object CMakeFiles/cmTC_514ca.dir/src.cxx.o
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -DHAVE_GETTIME  -std=gnu++17 -MD -MT CMakeFiles/cmTC_514ca.dir/src.cxx.o -MF CMakeFiles/cmTC_514ca.dir/src.cxx.o.d -o CMakeFiles/cmTC_514ca.dir/src.cxx.o -c /Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-ZhDgO4/src.cxx
        Linking CXX executable cmTC_514ca.js
        /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/cmTC_514ca.dir/link.txt --verbose=1
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -L/usr/local/include  @CMakeFiles/cmTC_514ca.dir/objects1.rsp -o cmTC_514ca.js
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/FindWrapRt.cmake:34 (check_cxx_source_compiles)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:145 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/Qt6Config.cmake:196 (find_package)"
      - "CMakeLists.txt:8 (find_package)"
    checks:
      - "Performing Test HAVE_SHM_OPEN_SHM_UNLINK"
    directories:
      source: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-zJGVAX"
      binary: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-zJGVAX"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/include"
      CMAKE_MODULE_PATH: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/platforms;/Users/stahlber/Projects/emsdk/upstream/emscripten/cmake/Modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_SHM_OPEN_SHM_UNLINK"
      cached: true
      stdout: |
        Change Dir: '/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-zJGVAX'
        
        Run Build Command(s): /opt/homebrew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_4a409/fast
        /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_4a409.dir/build.make CMakeFiles/cmTC_4a409.dir/build
        Building CXX object CMakeFiles/cmTC_4a409.dir/src.cxx.o
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -DHAVE_SHM_OPEN_SHM_UNLINK  -std=gnu++17 -MD -MT CMakeFiles/cmTC_4a409.dir/src.cxx.o -MF CMakeFiles/cmTC_4a409.dir/src.cxx.o.d -o CMakeFiles/cmTC_4a409.dir/src.cxx.o -c /Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-zJGVAX/src.cxx
        Linking CXX executable cmTC_4a409.js
        /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4a409.dir/link.txt --verbose=1
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -L/usr/local/include  @CMakeFiles/cmTC_4a409.dir/objects1.rsp -o cmTC_4a409.js
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:104 (try_compile)"
      - "/opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake:58 (cmake_check_source_compiles)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake:128 (check_cxx_source_compiles)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_third_party_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:43 (include)"
      - "/opt/homebrew/share/cmake/Modules/CMakeFindDependencyMacro.cmake:78 (find_package)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:145 (find_dependency)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:43 (include)"
      - "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/Qt6Config.cmake:196 (find_package)"
      - "CMakeLists.txt:8 (find_package)"
    checks:
      - "Performing Test HAVE_EGL"
    directories:
      source: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-rfFVXx"
      binary: "/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-rfFVXx"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/usr/local/include"
      CMAKE_MODULE_PATH: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/platforms;/Users/stahlber/Projects/emsdk/upstream/emscripten/cmake/Modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/Users/stahlber/Qt/6.8.3/wasm_singlethread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_EGL"
      cached: true
      stdout: |
        Change Dir: '/Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-rfFVXx'
        
        Run Build Command(s): /opt/homebrew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_90075/fast
        /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_90075.dir/build.make CMakeFiles/cmTC_90075.dir/build
        Building CXX object CMakeFiles/cmTC_90075.dir/src.cxx.o
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -DHAVE_EGL  -std=gnu++17 -MD -MT CMakeFiles/cmTC_90075.dir/src.cxx.o -MF CMakeFiles/cmTC_90075.dir/src.cxx.o.d -o CMakeFiles/cmTC_90075.dir/src.cxx.o -c /Users/stahlber/Projects/ft/build_wasm/CMakeFiles/CMakeScratch/TryCompile-rfFVXx/src.cxx
        Linking CXX executable cmTC_90075.js
        /opt/homebrew/bin/cmake -E cmake_link_script CMakeFiles/cmTC_90075.dir/link.txt --verbose=1
        /Users/stahlber/Projects/emsdk/upstream/emscripten/em++ -L/usr/local/include  @CMakeFiles/cmTC_90075.dir/objects1.rsp -o cmTC_90075.js
        
      exitCode: 0
...
